package com.bbva.wallet.exceptions;

public enum ErrorCodes {
    DUPLICATE_EMAIL,
    INVALID_VALUE,
    FAILED_AUTHENTICATION,
    TRANSACTION_NOT_FOUND,
    INSUFICIENT_BALANCE,
    ACCOUNT_NOT_FOUND,
    DELETED_USER,
    ACCESS_DENIED,
    EXPIRED_JWT,
    INVALID_JWT_SIGNATURE,
    MALFORMED_JWT,
    UNSUPPORTED_JWT,
    INVALID_JWT_ARGUMENT,
    INVALID_URL_REQUEST,
    INSUFFICIENT_FUNDS,
}

